#!/usr/bin/env python3
"""Builds dist/story_generalization_v2_exact_waveform.py — one self-contained
file for a Kaggle cell — by concatenating the modules in dependency order and
removing their local-import blocks. The Kaggle file therefore runs exactly the
same render/measure/optimizer code that the offline replay and tests verify."""

import ast
import hashlib
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
MODULES = ["audio_io.py", "run_seed.py", "scoring_engine.py", "story_analysis.py", "cue_sheet.py", "music_analysis.py", "arrangement.py", "music_generation.py", "mix_engineering.py", "pipeline.py"]
OUT = HERE / "dist" / "story_generalization_v2_exact_waveform.py"

LOCAL_BLOCK = re.compile(r"# <local-imports>.*?# </local-imports>\n", re.S)

HEADER = '''# ============================================================
# STORY SCORING LAB — GENERALIZATION V2 — EXACT WAVEFORM OPTIMIZER
# Single-file Kaggle build. GENERATED by build_kaggle_script.py —
# edit the modules in story_scoring_v2/, not this file.
#
# Kaggle: paste into one cell (Stable Audio stack already installed,
# HF_TOKEN secret set) and run. Defaults:
#   input  /kaggle/input   (stories 71, 72, 86; WAV preferred; 85 excluded)
#   output /kaggle/working/story_generalization_v2_exact_waveform/
#   zip    /kaggle/working/story_generalization_v2_exact_waveform.zip
# Source digest: {digest}
# ============================================================
'''


def _aliases(block):
    """`from m import a as b` inside a local-imports block becomes `b = a`
    in the single file (the names themselves are already defined there)."""
    lines = []
    for node in ast.walk(ast.parse(block)):
        if isinstance(node, ast.ImportFrom):
            lines += [f"{a.asname} = {a.name}" for a in node.names if a.asname and a.asname != a.name]
    return "".join(line + "\n" for line in lines)


def build():
    parts = []
    digest = hashlib.sha256()
    for name in MODULES:
        text = (HERE / name).read_text(encoding="utf-8")
        digest.update(text.encode("utf-8"))
        stripped, count = LOCAL_BLOCK.subn(lambda m: _aliases(m.group(0)), text)
        if name in ("music_generation.py", "pipeline.py") and count != 1:
            raise SystemExit(f"{name}: expected exactly one local-imports block, found {count}")
        if name != "pipeline.py":
            stripped = stripped.replace('\nif __name__ == "__main__":', "\nif False:")
        parts.append(f"\n# ##########  {name}  ##########\n\n{stripped}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(HEADER.format(digest=digest.hexdigest()[:16]) + "".join(parts), encoding="utf-8")
    compile(OUT.read_text(encoding="utf-8"), str(OUT), "exec")
    print(f"Wrote {OUT} ({sum(1 for _ in OUT.open(encoding='utf-8'))} lines)")
    return OUT


if __name__ == "__main__":
    build()
